#!/bin/bash

LAB=$1
GRAMMAR=$2
EXPR=$3

mkdir -p $LAB/build
cd $LAB

echo "Running ANTLR..."
java -jar /opt/antlr-4.7.1-complete.jar $GRAMMAR.g4 -o build/

echo "Compiling java files generated by ANTLR..."
cd build/
javac $GRAMMAR*.java

echo "Entering TestRig"
java org.antlr.v4.gui.TestRig $GRAMMAR $EXPR -gui

echo "Removing build files..."
cd ..
rm -rf build/
cd ..

